services:
  airflow:
    image: apache/airflow:2.10.4
    container_name: portfolio_clima_airflow
    command: standalone
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"