services:
  airflow:
    build: .
    image: portfolio-clima-airflow:latest
    container_name: portfolio_clima_airflow
    command: standalone
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./src:/opt/airflow/src
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
      - ${AWS_CREDENTIALS_PATH}:/home/airflow/.aws:ro
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}